version: '3.8'
services:
  app:
      container_name: "app"
      # Note that the path of the Dockerfile and context is relative to the *primary*
      # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
      # array). The sample below assumes your primary file is in the root of your project.
      build:
        context: .
        dockerfile: .devcontainer/Dockerfile
        args:
          VARIANT: "3-bullseye"
          NODE_VERSION: "none"
          EXTRA_CERTS: "include"

      volumes:
        - .:/workspace:cached
      command: /bin/sh -c "while sleep 1000; do :; done"
      environment:
        - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
